site_name: ANHYDEV
theme:
  name: 'material'
  logo: assets/logo.png
  favicon: assets/favicon.ico
  
  font:
    text: Ubuntu
  
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.footer
    - navigation.expand
    - navigation.top
    - navigation.tabs
    
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: grey
      accent: light blue
       
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: light blue
      
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/AnhyDev
      
    - icon: fontawesome/brands/x-twitter 
      link: https://x.com/AnhyDev
      
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/ubkyHWuSzD

copyright: Copyright &copy; 2015 - 2024 Anhydrite (ANHY)

repo_url: https://github.com/AnhyDev/AnhyFamily

nav:
  - Home: README.md
  - ANHYLIBAPI:
    - Plugin Documentation: anhylibapi/README.md
    - Details: anhylibapi/details.md
    - Usage: anhylibapi/usage.md
  - ANHYFAMILY:
    - Plugin Documentation: anhyfamily/README.md
    - COMMANDS:
        - Commands: anhyfamily/commands.md
    - PERSONALIZATION:
        - Player Gender: anhyfamily/gender.md
        - "Name and Surname": anhyfamily/names.md
    - FAMILY:
      - Marriage: anhyfamily/marry.md
      - Adoption: anhyfamily/adopt.md
      - Separation of Family Ties: anhyfamily/separate.md
      - Info Block: anhyfamily/info.md
    - FAMILY FUNCTIONS:
      - Family Prefix: anhyfamily/prefix.md
      - Family Chat: anhyfamily/chat.md
      - Family Home: anhyfamily/home.md
      - Family Chest: anhyfamily/chest.md
    - PAYMENTS:
      - Payment in Virtual Currency: anhyfamily/vault.md
      - Payment in Items: anhyfamily/items.md
      - Payment in Cryptocurrency: anhyfamily/crypto.md
    - ADDITIONAL:
      - Hugs: anhyfamily/hugs.md
      - Configuration File: anhyfamily/config.md
      - Placeholders: anhyfamily/placeholders.md
      - Permissions: anhyfamily/permissions.md
  - ANHYLINGO:
    - Plugin Documentation: anhylingo/README.md
    - Commands: anhylingo/commands.md
    - PersistentDataContainer: anhylingo/nbt_tags.md
    - File Management: anhylingo/files.md
    - Configuration: anhylingo/configuration.md
    - API AnhyLingo: anhylingo/api.md
  - ANHYSHOP:
    - Plugin Documentation: anhyshop/README.md
    - Commands: anhyshop/commands.md
    - Trading Operations: anhyshop/trading_operations.md
    - Dependencies: anhyshop/dependencies.md
  - ANHYREPO:
    - Plugin Documentation: anhyrepo/README.md
    - Features: anhyrepo/features.md
    - Commands: anhyrepo/commands.md
    - Interface: anhyrepo/interface.md
    - Use Cases: anhyrepo/use_cases.md
  - UTILS:
    - Text Utils: utils/utils.md
